name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-job:
    name: Checking source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: git config
        env:
          USER_NAME: ${{ github.event.pusher.name }}
          USER_EMAIL: ${{ github.event.pusher.email }}
        run: |
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"
      - name: Install packages
        run: npm install
      - name: Prettier
        run: npm run prettier
      - name: ESLint
        run: npm run lint
      - name: deploy
        run: npm run deploy
